package POJO;
// Generated Oct 14, 2022 9:20:41 AM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * TblAdmin generated by hbm2java
 */
@ManagedBean
public class TblAdmin  implements java.io.Serializable {


     private Integer idAdmin;
     private String name;
     private String email;
     private String password;
    
    public String save_admin() {
        DAOLogin add = new DAOLogin();
        return add.add_admin(this);
    }
     
    public String login_admin() {
        DAOLogin admDao = new DAOLogin();
        List<TblAdmin> adm = admDao.getBy(email, password);
        try {
            if (adm != null) {
                email = adm.get(0).email;
                password = adm.get(0).password;
                return "dashboard";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "login_error";
    }
     
    public TblAdmin() {
    }

    public TblAdmin(String name, String email, String password) {
       this.name = name;
       this.email = email;
       this.password = password;
    }
   
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


